### ISSUE TITLE
Morning peer-to-peer review - 7th Feb 2023

### ISSUE THREAD

**Issue by serengia** [hienphan0111/JS-capstone-project#23]
Hello @rivasbolinga  and @hienphan0111 . You code looks nice and well organized. To make it even better, you can consider the following change.
- Make getData function more modular by removing the functionality to populate UI. https://github.com/hienphan0111/JS-capstone-project/blob/1ae3f5829ad67b5bc283237796b71e1d709e2d4c/src/modules/api.js#L3-L7

**Comment by ghost** [comment]
Thanks, will do!!!!
